// AI-only customers — shown with a sparkle icon and filterable on the Feedback page.
// Names are stored lowercase for case-insensitive matching.

const AI_CUSTOMER_LIST = [
  'pied piper', 'koin games', 'myplace inc', 'new sapience, inc.', 'vital audio inc.',
  'troupe.ai', 'anomaly labs, inc', 'gumball digital, llc', 'linqalpha, inc.',
  'codex health, inc.', 'glencoco', 'smart scout', 'elula inc.', 'luminous',
  'brainjar inc.', 'dailyhuman inc.', 'mountain health', 'growthsphere.ai',
  'materials xyz, llc', 'kidneymetrix', 'ensemble ai', 'new frontier aerospace, inc.',
  'rampfuel', 'franki inc', 'the gradient group', 'diversifi.ai', 'proxy foods inc.',
  'termblocks', 'chirpy', 'the applyai', 'orkestra llc', 'epicurate inc', 'full fifty',
  'leaderworks, inc.', 'penrose', 'clearmatrix', 'iep&me, inc', 'bodo.ai', 'adslux llc',
  'parse ai', 'naitur', 'productnow', 'skyrelis', 'formulaic', 'blockjoy, inc',
  'eq recruiting', 'move ai', 'jened', 'living strategy', 'pakked', 'limelight',
  'plickers', 'kolla corporation', 'dolly card', 'first touch inc', 'estes media',
  'velvet fs', 'chiara santi realtor llc', 'conti family trust', 'conti santi properties llc',
  'csp 30121 antelope road llc', 'csp antelope road llc', 'digital align inc',
  'secure-centric', 'galileo', 'falk mountain states llc', 'sales layer inc',
  'ko team llc', 'easy acquire.ai llc', 'decycle biosystems, inc.', 'wisdom.io',
  'data pulse media', 'the know', 'enrich', 'thinkist, pbc', 'corten studio',
  'horizon-neuro', 'rev llc dba', 'ground truth systems',
  'topline - expert revenue management', 'kiwi data inc.',
  'saama capital management v, llc', 'twin vc', 'gather ai', 'squadhelp ventures',
  'the game band', 'oddr, inc', 'matic robots inc', 'elv8 media llc',
  'branded bridge line', 'c-trax', 'modrinth', 'pneumatic software, inc.',
  'unkeyed, inc', 'relm', 'rella inc', 'screenspace', 'theseus ai inc.', 'urbanum',
  'futurian systems - vail valley llc', 'tim porthouse coaching', 'drop vault', 'agapé',
  'storylane inc', 'bead pay inc', 'violet ai, inc.', 'civicreach.ai',
  'sigmoid health, inc.', 'ivot financial training', 'mirc capital', 'proshort',
  'phalanx', 'inventive ai', 'deepmm', 'foggy creek farm', 'bentlight', 'climatewells',
  'greens ai', 'imachines inc', 'outsider labs, inc (co/ai)', 'padgea',
  'havoc management', 'millions of monsters, inc.', 'mixergy', 'kindhealth', 'a79.ai',
  'cascade space', 'moxie robots', 'cashmere ai', 'ritten, inc', 'realestateapi',
  'miresource', 'crisp restaurant systems', 'xeniapp', 'speedscale', 'breachbits, inc.',
  'winning creative', 'grind analytics llc', 'please assist me', 'qpilot.cloud',
  'lingopal', 'angler ai', 'distru inc', 'north.cloud', 'laboriq', 'avala',
  'rescripted', 'cleverx', 'provenonce', 'bubbles', 'atellos solutions',
  'akada software', 'dma tech solutions', 'safetaper', 'aloqia', 'truthset',
  'mortgage growth system', 'smashcut', 'asm sports', 'shihiko inc.',
  'motion picture exchange llc', 'maus software llc', 'thermal',
  'antares technologies, llc', 'kirklin solutions', 'shotquality', 'secure our city, inc.',
  'docnow ehr', 'flair technologies inc', 'helios', 'rudiment', 'wonderverse', 'cybera',
  'jia', 'turso', 'architect', 'neo.tax', 'xpertly.ai, inc', 'campusknot',
  'augmentus technologies inc', 'interweb, inc.', 'skidattl', 'cyberseclabs',
  'me4u, inc', 'cypherface technologies, inc.', 'rendr', 'meridian', 'clipp',
  'survival frog', 'magic of paws llc', 'waii, inc.', 'seven principles corporation',
  'hubble', 'omega benefits', 'needle', 'micro-dyn medical systems', 'pabtek llc',
  'dasha', 'medtrics lab llc', 'fenworks', 'nerd apply', 'pathivy', 'abc-plan, inc.',
  'arbor', 'pathways', '1build inc', 'xray tech, inc.', 'selma digital', 'hz holdings',
  'vamo', 'fields', 'internet connections', 'find arbor', 'bola ai',
  'magnataur consulting, llc', 'crew', 'stardust', 'uslege.ai', 'creatorspark inc.',
  'pin parrot', 'kollegio ai', 'imediasalesteam > imediaaudiences > reptidemedia',
  'big moxi games', 'iupana llc', 'chapter 2', 'worklution', 'argos identity inc',
  'dwelzi', 'simpliscreen', 'advanse, llc', 'blueprint', 'atd partners',
  'curietech ai', 'goinspo', 'complete care management partners, llc', 'cohart',
  'moneyhash', 'zero longevity science', 'blackleaf organic llc', 'carfilm',
  'krpr.pet', 'upkid, inc.', 'alpx med', 'tclub, inc.', 'dwelling management inc',
  'veras', 'sky high party rentals llc', 'shpr dallas', 'daisy health', 'privateauto',
  'haven connect', 'avoma, inc.', 'bevz inc', 'brite', 'blue people',
  'quick response fire supply llc', 'productside', 'lumeo', 'allio fintech corp',
  'virtualpbx', 'audience', 'augmen media', 'slapfive, inc.', 'vpm solutions',
  'daylight computer co.', 'breakr', '4d sight', 'pangram labs, inc', 'direction inc',
  'glass health', 'home campus', 'waterlily caregiving inc', 'caog llc',
  'michael anthony', 'muxy', 'optimeyes ai', 'pocketflows', 'arcwise',
  'productive.ai', 'bizly, inc.', 'followup crm', 'incredible dream studios, inc.',
  'ovation ventures', 'crew finance, inc.', 'benjamin capital partners inc.',
  'ventures fm', 'open babylon', 'defendershield', 'essential contributions, ltd',
  'the swarm', 'gardens interactive, inc.', 'roundtrip ev solutions inc',
  'seekmaro.com', 'agentweb', 'agent astra inc', '7e wellness', 'astral.now',
  'gamesalad, inc.', 'petasense inc', 'getro, inc.',
  'revgen networks, llc dba mergewifi', 'nexstreet',
]

export const AI_CUSTOMER_NAMES = new Set(AI_CUSTOMER_LIST)

/** Returns true if the company name (or its Chargebee canonical name) is in the AI customer list. */
export function isAiCustomer(companyName: string, cbName?: string | null): boolean {
  const a = companyName.toLowerCase().trim()
  const b = cbName?.toLowerCase().trim()
  return AI_CUSTOMER_NAMES.has(a) || (b != null && b !== '' && AI_CUSTOMER_NAMES.has(b))
}
